version: 35
jobs:
- name: CI
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageWithKanikoStep
    name: publish docker client image
    buildContext: client/
    output: !RegistryOutput
      destinations: git.churrer.xyz/churrer.xyz/house/house:0.3.0
    builtInRegistryAccessTokenSecret: registry-token
    moreOptions: --use-new-run --snapshot-mode=redo --cache=true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
#  - !BuildImageWithKanikoStep
#    name: publish docker server image
#    buildContext: server/
#    output: !RegistryOutput
#      destinations: git.churrer.xyz/churrer.xyz/house/house-server:0.2.0
#    builtInRegistryAccessTokenSecret: registry-token
#    moreOptions: --use-new-run --snapshot-mode=redo --cache=true
#    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
    projects: churrer.xyz/house
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
