on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Install Doctl
        uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: read package.json
        uses: rexdefuror/read-package-json@v1.0.5

      - name: Build client container image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/house:${{ env.PACKAGE_VERSION }} ./client

      - name: Build server container image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/house-server:${{ env.PACKAGE_VERSION }} ./server

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push client image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/house:${{ env.PACKAGE_VERSION }}

      - name: Push server image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/house-server:${{ env.PACKAGE_VERSION }}