name: building churrer.xyz

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get version
        uses: xile611/read-package-version-action@v2.1
        id: version

      - name: log in to github container registry
        run: docker login https://ghcr.io -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_TOKEN }}

      - name: build client docker image
        run: docker build ./client/ --tag ghcr.io/danilomurer/churrer.xyz:${{ steps.version.outputs.current_version }}

      - name: publish client docker image
        run: docker push ghcr.io/danilomurer/churrer.xyz:${{ steps.version.outputs.current_version }}



